name = "food-sync"
main = "src/index.js"
compatibility_date = "2025-12-05"
keep_vars = true

routes = [
  "czbpght.cn/food*",
  "czbpght.cn/ledger*"
]


[assets]
directory = "../Chenxiang_Space"

[[d1_databases]]
binding = "MY_DB"
database_name = "food-db"
database_id = "8c890fa4-43db-42a3-a3be-d2596ec96f20"
